// For backwards compatibility
import { BaseAuthOptions, OrgMemberInfo, User, UserClass } from "@propelauth/node"

export {
    AccessTokenCreationException,
    AddUserToOrgException,
    ApiKeyCreateException,
    ApiKeyDeleteException,
    ApiKeyFetchException,
    ApiKeyUpdateException,
    ApiKeyValidateException,
    ApiKeyValidateRateLimitedException,
    BadRequestException,
    ChangeUserRoleInOrgException,
    CreateOrgException,
    CreateUserException,
    FeatureGatedException,
    ForbiddenException,
    IncorrectMfaCodeException,
    InvalidRequestFieldsException,
    MagicLinkCreationException,
    MfaNotEnabledException,
    MigrateUserException,
    MigrateUserPasswordException,
    Org,
    OrgIdToOrgMemberInfo,
    RemoveUserFromOrgException,
    RevokePendingOrgInviteException,
    toOrgIdToOrgMemberInfo,
    toUser,
    UnauthorizedException,
    UnexpectedException,
    UpdateOrgException,
    UpdateUserEmailException,
    UpdateUserMetadataException,
    UpdateUserPasswordException,
    UserAndOrgMemberInfo,
    UserClass,
    UserMetadata,
    UserNotFoundException,
    ApiKeyImportException,
    MigrateOrgToIsolatedException
} from "@propelauth/node"
export type {
    AccessToken,
    AddUserToOrgRequest,
    ApiKeyFull,
    ApiKeyNew,
    ApiKeyResultPage,
    ApiKeysCreateRequest,
    ApiKeysQueryRequest,
    ApiKeyUpdateRequest,
    ApiKeyValidation,
    ChangeUserRoleInOrgRequest,
    CreateAccessTokenRequest,
    CreatedOrg,
    CreatedUser,
    CreateMagicLinkRequest,
    CreateOrgRequest,
    CreateUserRequest,
    CustomRoleMapping,
    CustomRoleMappings,
    FetchSamlSpMetadataResponse,
    IdpProvider,
    InternalOrgMemberInfo,
    InternalUser,
    InviteUserToOrgRequest,
    LoginMethod,
    MagicLink,
    MigrateUserFromExternalSourceRequest,
    MigrateUserPasswordRequest,
    OrgApiKeyValidation,
    OrgQuery,
    OrgQueryResponse,
    PersonalApiKeyValidation,
    RemoveUserFromOrgRequest,
    RevokePendingOrgInviteRequest,
    SamlLoginProvider,
    SetSamlIdpMetadataRequest,
    SocialLoginProvider,
    StepUpMfaGrantType,
    StepUpMfaVerifyGrantResponse,
    StepUpMfaVerifyTotpResponse,
    TokenVerificationMetadata,
    UpdateOrgRequest,
    UpdateUserEmailRequest,
    UpdateUserMetadataRequest,
    UpdateUserPasswordRequest,
    UserInOrgMetadata,
    UserProperties,
    UserSignupQueryParams,
    UsersInOrgPagedResponse,
    UsersInOrgQuery,
    UsersPagedResponse,
    UsersQuery,
    VerifyStepUpGrantRequest,
    VerifyTotpChallengeRequest,
    SendSmsMfaCodeRequest,
    SendSmsMfaCodeRequestResponse,
    VerifySmsChallengeRequest,
    VerifySmsChallengeResponse,
    InviteUserToOrgByUserIdRequest,
    FetchUserMfaMethodsResponse,
    ApiKeyUsageQueryRequest,
    ApiKeyUsageQueryResponse,
    ApiKeysImportRequest,
    Employee,
    MfaPhoneType,
    MfaPhones,
    MfaTotpType,
    ScimGroup,
    ScimGroupResultPage,
    ScimGroupResult,
    ScimGroupMember,
    FetchOrgScimGroupsRequest,
    FetchScimGroupRequest,
    SetOidcIdpMetadataRequestBase,
    SetGenericOidcMetadataRequest,
    SetOktaOidcMetadataRequest,
    SetAzureOidcMetadataRequest,
    SetOidcIdpMetadataRequest,
    SocialLoginTokenProvider,
    SocialLoginToken,
    SocialLoginTokensResponse,
} from "@propelauth/node"
export {
    ReengagementReportInterval,
    ChampionReportInterval,
    ChurnReportInterval,
    GrowthReportInterval,
    AttritionReportInterval,
    TopInviterReportInterval,
    ChartMetric,
    ChartMetricCadence,
} from "@propelauth/node"
export type {
    ReportPagination,
    UserReport,
    UserReportRecord,
    OrgReport,
    OrgReportRecord,
    UserOrgMembershipForReport,
    ChartData,
    ChartDataPoint,
} from "@propelauth/node"
export { AuthOptions, initAuth } from "./auth"
export type {
    InitAuthResult,
    RequireOrgMemberArgs,
    RequireOrgMemberWithMinimumRoleArgs,
    RequireOrgMemberWithExactRoleArgs,
    RequireOrgMemberWithPermissionArgs,
    RequireOrgMemberWithAllPermissionsArgs,
} from "./auth"
export type { BaseAuthOptions, User, OrgMemberInfo }

declare global {
    namespace Express {
        interface Request {
            user?: User
            userClass?: UserClass
            org?: OrgMemberInfo
        }
    }
}
